### PR TITLE
rebase with upstream

### PR DESCRIPTION
**Pull request by fr500**

### CODE REVIEW

**Comment by Nikolaj64** [comment]
Did you intend to make this pull request on StapleButter's repo? Shouldn't it be for libretro/melonDS?

**Comment by twinaphex** [comment]
Well we'd like to contribute to upstream if possible.

**Comment by Nikolaj64** [comment]
Ah okay then, my bad :)
Having libretro support upstream would be nice.

**Comment by fr500** [comment]
it was still a mistake though :p but I wouldn't mind it being merged although I messed up some commits when rebasing.

**Pull request closed without merging**
